//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Završni___Vozni_red_vlakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoTrain_Lines
    {
        public int ID { get; set; }
        public Nullable<int> Broj_lokomotive { get; set; }
        public string Mjesto_polaska { get; set; }
        public string Mjesto_dolaska { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_polaska { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_dolaska { get; set; }
        public string Vrsta_tereta { get; set; }
        public string Kolicina_tereta { get; set; }
        public Nullable<double> Tezina_tereta_tona_ { get; set; }
    }
}
