//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Završni___Vozni_red_vlakova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZR_VozniRedVlakovaEntities : DbContext
    {
        public ZR_VozniRedVlakovaEntities()
            : base("name=ZR_VozniRedVlakovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Train_Lines> Train_Lines { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
