//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Završni___Vozni_red_vlakova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_Lines
    {
        public int ID { get; set; }
        public Nullable<int> Broj_PutnickeLinije { get; set; }
        public Nullable<int> Broj_Lokomotive { get; set; }
        public string Smjer_Kretanja { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_Dolaska { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_Odlaska { get; set; }
        public string Brzi_Vlak { get; set; }
        public Nullable<int> Peron { get; set; }
        public Nullable<int> Kolosijek { get; set; }
        public string Vrijeme_Kašnjenja { get; set; }
    }
}
